### ISSUE TITLE
I get an empty page and some erros

### ISSUE THREAD

**Issue by BerndGewehr** [rthiney/ionic2-azure-auth#1]
Hi, i did want to check this repo as we are looking for a new approach to publish some enterprise apps for mobile devices with AzureAD auth.

I installed the solution right from git to my local VS2015 workspace, npm install runs without errors, gulpfile is executed, build folder created, then the chrome opens the riddle emulator of android - with a blank page and some errors.

Can you push me into the right direction to use this? 

````
console.clear
ripple.js (37,13537)
Ripple :: Environment Warming Up (Tea. Earl Grey. Hot.)
ripple.js (37,14889)
cordova :: Setting the user agent server side failed.
ripple.js (37,14889)
cordova :: Initialization Finished (Make it so.)
ripple.js (37,14889)
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
app.bundle.js (28763,13)
DEVICE READY FIRED AFTER
app.bundle.js (75904,13)
cordova :: Native back button handler was detached.
ripple.js (37,14889)
Native: tried calling StatusBar.styleDefault, but the StatusBar plugin is not installed.
app.bundle.js (82633,17)
Install the StatusBar plugin: 'cordova plugin add cordova-plugin-statusbar'
app.bundle.js (82638,13)
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: ReferenceError: WindowsAzure is not defined
ORIGINAL STACKTRACE:
ReferenceError: WindowsAzure is not defined
    at new DataPage (http://localhost:4400/build/js/app.bundle.js:113:26)
    at _View_DataPage_Host0.createInternal (DataPage_Host.template.js:15:24)
    at _View_DataPage_Host0.AppView.create (http://localhost:4400/build/js/app.bundle.js:29820:21)
    at _View_DataPage_Host0.DebugAppView.create (http://localhost:4400/build/js/app.bundle.js:30032:44)
    at ComponentFactory.create (http://localhost:4400/build/js/app.bundle.js:29049:36)
    at http://localhost:4400/build/js/app.bundle.js:54371:49
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:232:26)
    at Object.onInvoke (http://localhost:4400/build/js/app.bundle.js:35274:41)
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:231:32)
    at Zone.run (http://localhost:4400/build/js/zone.js:114:43)
ERROR CONTEXT:
[object Object]
app.bundle.js (38429,28)
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: ReferenceError: WindowsAzure is not defined
ORIGINAL STACKTRACE:
ReferenceError: WindowsAzure is not defined
    at new DataPage (http://localhost:4400/build/js/app.bundle.js:113:26)
    at _View_DataPage_Host0.createInternal (DataPage_Host.template.js:15:24)
    at _View_DataPage_Host0.AppView.create (http://localhost:4400/build/js/app.bundle.js:29820:21)
    at _View_DataPage_Host0.DebugAppView.create (http://localhost:4400/build/js/app.bundle.js:30032:44)
    at ComponentFactory.create (http://localhost:4400/build/js/app.bundle.js:29049:36)
    at http://localhost:4400/build/js/app.bundle.js:54371:49
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:232:26)
    at Object.onInvoke (http://localhost:4400/build/js/app.bundle.js:35274:41)
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:231:32)
    at Zone.run (http://localhost:4400/build/js/zone.js:114:43)
ERROR CONTEXT:
[object Object]
app.bundle.js (38420,28)
STACKTRACE:
app.bundle.js (38420,28)
Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: ReferenceError: WindowsAzure is not defined
ORIGINAL STACKTRACE:
ReferenceError: WindowsAzure is not defined
    at new DataPage (http://localhost:4400/build/js/app.bundle.js:113:26)
    at _View_DataPage_Host0.createInternal (DataPage_Host.template.js:15:24)
    at _View_DataPage_Host0.AppView.create (http://localhost:4400/build/js/app.bundle.js:29820:21)
    at _View_DataPage_Host0.DebugAppView.create (http://localhost:4400/build/js/app.bundle.js:30032:44)
    at ComponentFactory.create (http://localhost:4400/build/js/app.bundle.js:29049:36)
    at http://localhost:4400/build/js/app.bundle.js:54371:49
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:232:26)
    at Object.onInvoke (http://localhost:4400/build/js/app.bundle.js:35274:41)
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:231:32)
    at Zone.run (http://localhost:4400/build/js/zone.js:114:43)
ERROR CONTEXT:
[object Object]
    at resolvePromise (http://localhost:4400/build/js/zone.js:468:31)
    at http://localhost:4400/build/js/zone.js:505:17
    at ZoneDelegate.invokeTask (http://localhost:4400/build/js/zone.js:265:35)
    at Object.onInvokeTask (http://localhost:4400/build/js/app.bundle.js:35265:41)
    at ZoneDelegate.invokeTask (http://localhost:4400/build/js/zone.js:264:40)
    at Zone.runTask (http://localhost:4400/build/js/zone.js:154:47)
    at drainMicroTaskQueue (http://localhost:4400/build/js/zone.js:401:35)
app.bundle.js (38420,28)
console.groupEnd
app.bundle.js (38438,28)
Unhandled Promise rejection:
zone.js (388,21)
Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: ReferenceError: WindowsAzure is not defined
ORIGINAL STACKTRACE:
ReferenceError: WindowsAzure is not defined
    at new DataPage (http://localhost:4400/build/js/app.bundle.js:113:26)
    at _View_DataPage_Host0.createInternal (DataPage_Host.template.js:15:24)
    at _View_DataPage_Host0.AppView.create (http://localhost:4400/build/js/app.bundle.js:29820:21)
    at _View_DataPage_Host0.DebugAppView.create (http://localhost:4400/build/js/app.bundle.js:30032:44)
    at ComponentFactory.create (http://localhost:4400/build/js/app.bundle.js:29049:36)
    at http://localhost:4400/build/js/app.bundle.js:54371:49
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:232:26)
    at Object.onInvoke (http://localhost:4400/build/js/app.bundle.js:35274:41)
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:231:32)
    at Zone.run (http://localhost:4400/build/js/zone.js:114:43)
ERROR CONTEXT:
[object Object]
zone.js (390,17)
Current window: 
console.clear
ripple.js (37,13537)
Ripple :: Environment Warming Up (Tea. Earl Grey. Hot.)
ripple.js (37,14889)
cordova :: Setting the user agent server side failed.
ripple.js (37,14889)
cordova :: Initialization Finished (Make it so.)
ripple.js (37,14889)
DEVICE READY FIRED AFTER
app.bundle.js (75904,13)
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
app.bundle.js (28763,13)
cordova :: Native back button handler was detached.
ripple.js (37,14889)
Native: tried calling StatusBar.styleDefault, but the StatusBar plugin is not installed.
app.bundle.js (82633,17)
Install the StatusBar plugin: 'cordova plugin add cordova-plugin-statusbar'
app.bundle.js (82638,13)
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: ReferenceError: WindowsAzure is not defined
ORIGINAL STACKTRACE:
ReferenceError: WindowsAzure is not defined
    at new DataPage (http://localhost:4400/build/js/app.bundle.js:113:26)
    at _View_DataPage_Host0.createInternal (DataPage_Host.template.js:15:24)
    at _View_DataPage_Host0.AppView.create (http://localhost:4400/build/js/app.bundle.js:29820:21)
    at _View_DataPage_Host0.DebugAppView.create (http://localhost:4400/build/js/app.bundle.js:30032:44)
    at ComponentFactory.create (http://localhost:4400/build/js/app.bundle.js:29049:36)
    at http://localhost:4400/build/js/app.bundle.js:54371:49
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:232:26)
    at Object.onInvoke (http://localhost:4400/build/js/app.bundle.js:35274:41)
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:231:32)
    at Zone.run (http://localhost:4400/build/js/zone.js:114:43)
ERROR CONTEXT:
[object Object]
app.bundle.js (38429,28)
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: ReferenceError: WindowsAzure is not defined
ORIGINAL STACKTRACE:
ReferenceError: WindowsAzure is not defined
    at new DataPage (http://localhost:4400/build/js/app.bundle.js:113:26)
    at _View_DataPage_Host0.createInternal (DataPage_Host.template.js:15:24)
    at _View_DataPage_Host0.AppView.create (http://localhost:4400/build/js/app.bundle.js:29820:21)
    at _View_DataPage_Host0.DebugAppView.create (http://localhost:4400/build/js/app.bundle.js:30032:44)
    at ComponentFactory.create (http://localhost:4400/build/js/app.bundle.js:29049:36)
    at http://localhost:4400/build/js/app.bundle.js:54371:49
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:232:26)
    at Object.onInvoke (http://localhost:4400/build/js/app.bundle.js:35274:41)
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:231:32)
    at Zone.run (http://localhost:4400/build/js/zone.js:114:43)
ERROR CONTEXT:
[object Object]
app.bundle.js (38420,28)
STACKTRACE:
app.bundle.js (38420,28)
Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: ReferenceError: WindowsAzure is not defined
ORIGINAL STACKTRACE:
ReferenceError: WindowsAzure is not defined
    at new DataPage (http://localhost:4400/build/js/app.bundle.js:113:26)
    at _View_DataPage_Host0.createInternal (DataPage_Host.template.js:15:24)
    at _View_DataPage_Host0.AppView.create (http://localhost:4400/build/js/app.bundle.js:29820:21)
    at _View_DataPage_Host0.DebugAppView.create (http://localhost:4400/build/js/app.bundle.js:30032:44)
    at ComponentFactory.create (http://localhost:4400/build/js/app.bundle.js:29049:36)
    at http://localhost:4400/build/js/app.bundle.js:54371:49
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:232:26)
    at Object.onInvoke (http://localhost:4400/build/js/app.bundle.js:35274:41)
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:231:32)
    at Zone.run (http://localhost:4400/build/js/zone.js:114:43)
ERROR CONTEXT:
[object Object]
    at resolvePromise (http://localhost:4400/build/js/zone.js:468:31)
    at http://localhost:4400/build/js/zone.js:505:17
    at ZoneDelegate.invokeTask (http://localhost:4400/build/js/zone.js:265:35)
    at Object.onInvokeTask (http://localhost:4400/build/js/app.bundle.js:35265:41)
    at ZoneDelegate.invokeTask (http://localhost:4400/build/js/zone.js:264:40)
    at Zone.runTask (http://localhost:4400/build/js/zone.js:154:47)
    at drainMicroTaskQueue (http://localhost:4400/build/js/zone.js:401:35)
app.bundle.js (38420,28)
console.groupEnd
app.bundle.js (38438,28)
Unhandled Promise rejection:
zone.js (388,21)
Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: ReferenceError: WindowsAzure is not defined
ORIGINAL STACKTRACE:
ReferenceError: WindowsAzure is not defined
    at new DataPage (http://localhost:4400/build/js/app.bundle.js:113:26)
    at _View_DataPage_Host0.createInternal (DataPage_Host.template.js:15:24)
    at _View_DataPage_Host0.AppView.create (http://localhost:4400/build/js/app.bundle.js:29820:21)
    at _View_DataPage_Host0.DebugAppView.create (http://localhost:4400/build/js/app.bundle.js:30032:44)
    at ComponentFactory.create (http://localhost:4400/build/js/app.bundle.js:29049:36)
    at http://localhost:4400/build/js/app.bundle.js:54371:49
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:232:26)
    at Object.onInvoke (http://localhost:4400/build/js/app.bundle.js:35274:41)
    at ZoneDelegate.invoke (http://localhost:4400/build/js/zone.js:231:32)
    at Zone.run (http://localhost:4400/build/js/zone.js:114:43)
ERROR CONTEXT:
[object Object]
zone.js (390,17)
Current window: 

````

**Comment by BerndGewehr** [comment]
I found the right way to install the statusbar cordova add on and most of the errors are gone. If i need further assistance, I wil come back with another issue.
